CREATE TABLE IF NOT EXISTS hosts(id TEXT PRIMARY KEY,writer_hash TEXT NOT NULL,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS readers(host TEXT NOT NULL,id TEXT NOT NULL,token_hash TEXT NOT NULL,PRIMARY KEY(host,id),FOREIGN KEY(host) REFERENCES hosts(id));
CREATE TABLE IF NOT EXISTS datasets(host TEXT NOT NULL,dataset TEXT NOT NULL,revision INTEGER NOT NULL,digest TEXT NOT NULL,payload TEXT NOT NULL,updated INTEGER NOT NULL,PRIMARY KEY(host,dataset),FOREIGN KEY(host) REFERENCES hosts(id));
CREATE TABLE IF NOT EXISTS invites(hash TEXT PRIMARY KEY,expires INTEGER NOT NULL,host TEXT);
CREATE TABLE IF NOT EXISTS budget(day TEXT PRIMARY KEY,n INTEGER NOT NULL);
