<script lang="ts">
 import {compact,cost,numeric,rows,stamp,type Row} from '../lib/api'; import {tr} from '../lib/i18n';
 export let data:Row[]=[]; export let title='Token 和费用趋势'; export let onselect:(r:Row)=>void=()=>{}; let enabled=['tokens','usd']; let hover=-1;
 const colors:Record<string,string>={tokens:'var(--tokens)',usd:'var(--cost)',user_requests:'var(--output)'};
 $: items=rows(data).slice(0,800); $: maxima=Object.fromEntries(['tokens','usd','user_requests'].map(k=>[k,Math.max(1,...items.map(r=>Number(r[k]??(k==='usd'?r.cost_usd:0))||0))]));
 function point(r:Row,i:number,k:string){return `${48+(i/Math.max(1,items.length-1))*690},${190-(Number(r[k]??(k==='usd'?r.cost_usd:0))||0)/maxima[k]*155}`;}
 function toggle(k:string){enabled=enabled.includes(k)?enabled.filter(x=>x!==k):[...enabled,k];}
 function textLabel(r:Row){return r.label??stamp(r.timestamp??r.date)}
</script>
<section class="surface chart-panel"><div class="row between"><h3>{tr(title)}</h3><div class="row legend">{#each [['tokens','总 Token'],['usd','费用'],['user_requests','用户请求']] as [key,label]}<button class:active={enabled.includes(key)} class="quiet" onclick={()=>toggle(key)}><i style:background={colors[key]}></i>{tr(label)}</button>{/each}</div></div>
{#if !items.length}<div class="empty small">{tr('暂无数据')}</div>{:else}<div class="chart-box"><svg class="chart" viewBox="0 0 770 235" role="img" aria-label={tr(title)}><path d="M48 35H738 M48 87H738 M48 139H738 M48 190H738" stroke="var(--grid)" fill="none"/>{#each enabled as k}<polyline points={items.map((r,i)=>point(r,i,k)).join(' ')} fill="none" stroke={colors[k]} stroke-width="2.5" stroke-linejoin="round"/>{/each}<text x="48" y="218" fill="var(--muted)" font-size="11">{textLabel(items[0])}</text><text x="738" y="218" text-anchor="end" fill="var(--muted)" font-size="11">{textLabel(items[items.length-1])}</text>{#each items as r,i}<rect x={48+i/Math.max(1,items.length-1)*690-5} y="28" width={Math.max(10,690/items.length)} height="169" fill="transparent" role="button" tabindex="0" aria-label={textLabel(r)} onmouseenter={()=>hover=i} onmouseleave={()=>hover=-1} onfocus={()=>hover=i} onblur={()=>hover=-1} onclick={()=>onselect(r)} onkeydown={e=>{if(e.key==='Enter')onselect(r)}}/>{/each}{#if hover>=0}<line x1={48+hover/Math.max(1,items.length-1)*690} x2={48+hover/Math.max(1,items.length-1)*690} y1="28" y2="190" stroke="var(--muted)" stroke-dasharray="3 4"/>{/if}</svg>{#if hover>=0}<div class="chart-tooltip"><strong>{textLabel(items[hover])}</strong><span>{tr('总 Token')} {numeric(items[hover].tokens)}</span><span>{tr('费用')} {cost(items[hover].usd??items[hover].cost_usd)}{items[hover].cost_complete===false?' · '+tr('部分定价'):''}</span><span>{tr('用户请求')} {numeric(items[hover].user_requests)}</span></div>{/if}</div><div class="row chart-axis"><span>{compact(maxima.tokens)} Token</span><span>{cost(maxima.usd)}</span></div>{/if}</section>
