<script lang="ts">
 import {onDestroy} from 'svelte';import {api,rows,text,number,compact,utcReportStamp,type Row} from '../lib/api';
 import {tr} from '../lib/i18n';
 export let data:Row={};export let settings:Row={};export let onsave:((r:Row)=>Promise<void>)|undefined;export let onerror:((e:any)=>void)|undefined;export let onpage:((direction:number)=>void)|undefined;
 let local=false,sort='weekly_limit_percent',page=0,visible=5;let expanded=new Set<string>();let width=700;let saved:Row={};let ranking:Row={},sequence=0;
 $: if(!local)void load(data.chat_usage,sort,page);
 onDestroy(()=>sequence++);
 async function load(_source:Row,metric:string,current:number){const ticket=++sequence;try{const result=await api('GetChatRanking',metric,current+1);if(ticket===sequence)ranking=result;}catch(e){if(ticket===sequence)onerror?.(e)}}
 $: storage=local?'usage-local-threads':'usage-threads';
 $: saved=settings.column_widths?.[storage]??{};
 $: candidates=local?rows(data.chats):rows(ranking.threads);
 $: pages=local?Math.max(1,Number(data.chat_pages??1)):Math.max(1,Number(ranking.pages??1));
 $: page=Math.min(page,pages-1);
 $: available=Math.max(430,width-24);
 $: credits=Math.min(available-200-(local?0:120),Math.max(100,Number(saved.credits??115)));
 $: weekly=local?0:Math.min(available-200-credits,Math.max(120,Number(saved.weekly??180)));
 $: chat=available-weekly-credits;
 $: shown=candidates.slice(0,visible);
 function observe(node:HTMLElement){const observer=new ResizeObserver(entries=>{width=entries[0].contentRect.width});observer.observe(node);return{destroy(){observer.disconnect()}}}
 function toggleMode(){local=!local;page=0;visible=5;expanded=new Set();sequence++;}
 function changeSort(next:string){sort=next;page=0;visible=5;expanded=new Set();}
 function changePage(direction:number){visible=5;expanded=new Set();if(local)onpage?.(direction);else page+=direction;}
 function toggle(id:string){const next=new Set(expanded);next.has(id)?next.delete(id):next.add(id);expanded=next;}
 function precise(value:any){const n=number(value);return n===null?'—':n.toLocaleString(undefined,{maximumFractionDigits:n>0&&n<.01?4:2})+'%';}
 function creditsText(value:any){const n=number(value);return n===null?'—':n.toLocaleString(undefined,{maximumFractionDigits:2});}
 function breakdown(row:Row,key:string){const total=number(row[sort]);const amounts=new Map<string,number>();for(const group of rows(row.groups)){const n=number(group[sort]);if(n!==null){const label=text(group[key],tr('未知'));amounts.set(label,(amounts.get(label)??0)+n);}}const result=Array.from(amounts,([label,value])=>({label,value})).sort((a,b)=>b.value-a.value);const rest=(total??0)-result.reduce((n,r)=>n+r.value,0);if(total!==null&&rest>Math.max(.000001,total*.0001))result.push({label:tr('未归类'),value:rest});return total!==null&&total>0?result.map(r=>({...r,percent:r.value/total*100})):[];}
 async function open(id:string){try{await api('OpenChat',id)}catch(e){onerror?.(e)}}
 async function refresh(){try{await api('RefreshAccountReports')}catch(e){onerror?.(e)}}
 function resize(event:PointerEvent,column:string){event.preventDefault();const node=event.currentTarget as HTMLElement;node.setPointerCapture(event.pointerId);const origin=event.clientX;const c=chat,w=weekly,u=credits;const initial={...saved};const move=(e:PointerEvent)=>{const delta=e.clientX-origin;if(column==='chat'){const next=local?u:w,minimum=local?100:120;const movement=Math.max(200-c,Math.min(next-minimum,delta));saved={...initial,[local?'credits':'weekly']:next-movement};}else{const movement=Math.max(120-w,Math.min(u-100,delta));saved={...initial,weekly:w+movement,credits:u-movement};}};const end=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',end);node.removeEventListener('pointercancel',end);void onsave?.({column_widths:{...(settings.column_widths??{}),[storage]:saved}}).catch(e=>onerror?.(e));};node.addEventListener('pointermove',move);node.addEventListener('pointerup',end);node.addEventListener('pointercancel',end);}
</script>
<section class="chat-ranking">
 <div class="ranking-heading"><h3>{tr(local?'本机 Token 排行':'聊天用量排行')}</h3><button class="quiet" onclick={toggleMode}>{tr(local?'查看额度排行':'本机 Token')}</button></div>
 {#if ranking.error&&!local}<p class="ranking-note">{ranking.error}</p>{/if}
 {#if !shown.length}<div class="ranking-empty">{tr(!local&&ranking.loading?'正在读取':'暂不可用')}<small>{tr(local?'暂无本机聊天记录':'当前账户尚未提供这项明细')}</small>{#if !local}<button onclick={refresh}>{tr('刷新明细')}</button>{/if}</div>
 {:else}<div class="ranking-scroll" use:observe><div class="ranking-grid" style:width={`${Math.max(454,width)}px`}>
  <div class="ranking-header" style:grid-template-columns={`${chat}px ${local?'':weekly+'px '}${credits}px`}><div>{tr('聊天')}<button class="column-handle" aria-label={tr('调整聊天列宽')} onpointerdown={e=>resize(e,'chat')}></button></div>{#if !local}<div><button class="sort-column" onclick={()=>changeSort('weekly_limit_percent')}>{tr('占每周限额的 %')}</button><button class="column-handle" aria-label={tr('调整额度列宽')} onpointerdown={e=>resize(e,'weekly')}></button></div>{/if}<button class="sort-column" onclick={()=>changeSort('balance_usage_credits')}>{tr(local?'Token':'已用额度')}</button></div>
  {#each shown as row}<div class:expanded={expanded.has(String(row.thread_id??row.session_id))} class="ranking-entry"><button class="ranking-row" style:grid-template-columns={`${chat}px ${local?'':weekly+'px '}${credits}px`} onclick={()=>toggle(String(row.thread_id??row.session_id))}><span class="chat-name"><span class="chevron">{expanded.has(String(row.thread_id??row.session_id))?'⌄':'›'}</span><span>{text(row.title??row.name??row.session_title??row.thread_id??row.session_id)}{#if row.data_status==='partial'}<small>{tr('部分数据')}</small>{/if}</span></span>{#if !local}<span>{precise(row.weekly_limit_percent)}</span>{/if}<span>{local?compact(row.local_tokens??row.tokens??row.total_tokens):creditsText(row.balance_usage_credits)}</span></button>
   {#if expanded.has(String(row.thread_id??row.session_id))}<div class="ranking-details">{#if !local}{#each [['model','模型'],['reasoning_effort','推理强度'],['speed','速度']] as [key,label]}<div class="breakdown"><span>{tr(label)}</span><div>{#each breakdown(row,key) as group}<div>{group.label}<small>{precise(group.percent)}</small></div>{:else}—{/each}</div></div>{/each}{/if}<button class="quiet" onclick={()=>open(String(row.thread_id??row.session_id))}>{tr('打开聊天 ↗')}</button></div>{/if}</div>{/each}
 </div></div><div class="ranking-footer">{#if visible<Math.min(25,candidates.length)}<button onclick={()=>visible=Math.min(25,visible+5)}>{tr('显示更多')}</button>{/if}<small>{!local?tr('统计截至')+' '+utcReportStamp(ranking.data_as_of):''}</small><div><button aria-label={tr('上一页')} disabled={local?Number(data.chat_page??1)<=1:!page} onclick={()=>changePage(-1)}>‹</button><span>{local?data.chat_page??1:page+1} / {pages}</span><button aria-label={tr('下一页')} disabled={local?Number(data.chat_page??1)>=pages:page+1>=pages} onclick={()=>changePage(1)}>›</button></div></div>{/if}
</section>
<style>
.chat-ranking{min-width:0;display:flex;flex-direction:column;gap:20px}.ranking-heading{display:flex;gap:12px;align-items:center}.ranking-heading h3{font-size:18px;margin:0}.ranking-heading button,.ranking-note,.ranking-footer small{font-size:11px;color:var(--muted)}.ranking-scroll{overflow-x:auto;border:1px solid var(--border);border-radius:18px}.ranking-header,.ranking-row{display:grid;align-items:center;padding:0 12px;min-height:54px}.ranking-header{color:var(--muted);font-size:12px}.ranking-header>div{height:54px;display:flex;align-items:center;justify-content:center;position:relative}.ranking-header>div:first-child{justify-content:flex-start;padding-left:30px}.column-handle{position:absolute;right:-4px;top:0;height:54px;width:8px;min-height:0;cursor:col-resize;touch-action:none;border:0;background:transparent;padding:0}.column-handle::after{content:'';position:absolute;left:4px;top:15px;width:1px;height:16px;background:var(--border)}.sort-column{border:0;background:transparent;font-size:12px;color:inherit;justify-content:center;width:100%;padding:0;min-height:28px}.ranking-entry{border-top:1px solid var(--border)}.ranking-entry.expanded{background:var(--soft)}.ranking-row{width:100%;text-align:center;border:0;border-radius:0;background:transparent;font-size:14px;min-height:64px;font-variant-numeric:tabular-nums}.chat-name{display:flex;align-items:center;text-align:left;padding:0 18px 0 0;gap:6px;min-width:0}.chat-name>span:last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chevron{width:18px;flex:none;color:var(--muted)}.chat-name small{display:block;color:var(--muted);font-size:10px}.ranking-details{padding:4px 53px 24px;display:flex;flex-direction:column;align-items:flex-start;gap:17px;font-size:14px}.breakdown{display:flex;gap:18px;align-items:flex-start}.breakdown>span{width:100px;color:var(--muted)}.breakdown>div{display:flex;flex-direction:column;gap:7px}.breakdown small{padding-left:8px;color:var(--muted);font-size:11px}.ranking-footer{display:flex;align-items:center;gap:12px;font-size:10px}.ranking-footer small{flex:1}.ranking-footer>div{display:flex;align-items:center;gap:10px}.ranking-footer button{font-size:11px;min-height:24px}.ranking-empty{padding:18px 0;display:flex;flex-direction:column;align-items:flex-start;gap:10px;font-size:13px}.ranking-empty small{color:var(--muted);font-size:11px}
</style>
