<script lang="ts">
 import {onDestroy}from'svelte';import {api,rows,text,kind,numeric,priced,stamp,type Row} from '../lib/api'; import {tr}from'../lib/i18n'; import Markdown from './Markdown.svelte'; import Model from './Model.svelte'; import Icon from './Icon.svelte';
 export let id=''; export let onerror:(e:any)=>void=()=>{}; let data:Row={}; let busy=false; let page=1; let sequence=0; let copied='';
 $: if(id) void load(id,1); else {data={};sequence++;}
 onDestroy(()=>sequence++);
 async function load(next:string,p:number){const ticket=++sequence;busy=true;try{const value=await api('GetDetails',next,p);if(ticket===sequence){data=value;page=p;}}catch(e){if(ticket===sequence)onerror(e)}finally{if(ticket===sequence)busy=false}}
 function body(v:any){return typeof v==='string'?v:text(v?.text??v?.content??v?.markdown,'')}
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);copied=label;setTimeout(()=>copied='',1800)}catch(e){onerror(e)}}
</script>
<aside class="inspector surface" aria-busy={busy}><h2>{data.request?.session_title??tr('请求详情')}</h2>{#if !id}<div class="empty">{tr('点击请求查看详情')}</div>{:else if busy&&!data.request}<div class="empty">{tr('正在加载')}</div>{:else}<div class="inspector-scroll"><section><div class="row between"><h3>{tr('原始请求')}</h3><button class="quiet" aria-label={tr('复制')} disabled={!body(data.user)} onclick={()=>copy(body(data.user),'user')}><Icon name={copied==='user'?'check':'copy'} size={15}/></button></div>{#if body(data.user)}<Markdown content={body(data.user)} {onerror}/>{:else}<p class="muted">{tr('暂无原始请求')}</p>{/if}{#if data.user_complete===false}<small class="warning">{tr('正文未完整保留')}</small>{/if}</section>
<section><Model record={data.request??{}}/><div class="detail-stats"><span>Token <b>{numeric(data.request?.total_tokens)}</b></span><span>{tr('费用')} <b>{priced(data.request??{})}</b></span><span>{tr('模型调用')} <b>{numeric(data.request?.call_count)}</b></span></div><small class="muted">{stamp(data.request?.timestamp)} · {text(data.request?.reasoning_effort)} · {text(data.request?.service_tier)}</small></section>
<section><div class="row between"><h3>{tr('最终回复')}</h3><button class="quiet" aria-label={tr('复制')} disabled={!body(data.final)} onclick={()=>copy(body(data.final),'final')}><Icon name={copied==='final'?'check':'copy'} size={15}/></button></div>{#if body(data.final)}<Markdown content={body(data.final)} {onerror}/>{:else}<p class="muted">{tr('暂无最终回复')}</p>{/if}{#if data.final_complete===false}<small class="warning">{tr('正文未完整保留')}</small>{/if}</section>
{#if rows(data.attachments).length}<section><h3>{tr('附件')}</h3>{#each rows(data.attachments) as a}<div class="attachment"><Icon name="report" size={15}/><span>{text(a.name??a.filename??a.path??a.type)}</span></div>{/each}</section>{/if}
<section><h3>{tr('调用组成')}</h3>{#each rows(data.composition) as c}<div class="composition"><Model record={c}/><span>× {numeric(c.call_count??c.count)} · {priced(c)} · {numeric(c.total_tokens??c.tokens)} Token</span></div>{/each}{#each rows(data.members) as m}<button class="member quiet" onclick={()=>load(String(m.id),1)}><span>{kind(m.record_kind)} · {text(m.model)}</span><small>{priced(m)} · {numeric(m.total_tokens)} Token</small></button>{/each}{#if Number(data.pages)>1}<div class="row"><button disabled={page<=1||busy} onclick={()=>load(id,page-1)}>{tr('上一页')}</button><span>{page} / {data.pages}</span><button disabled={page>=data.pages||busy} onclick={()=>load(id,page+1)}>{tr('下一页')}</button></div>{/if}</section>
<details><summary>IDs</summary><p class="mono">{text(data.request?.turn_id)}<br/>{text(data.request?.session_id)}<br/>{text(data.request?.id)}</p></details></div>{/if}</aside>
