<script lang="ts">
 import {onDestroy} from 'svelte';import {type Query,type Row,rows} from '../lib/api';import{tr}from'../lib/i18n';
 export let query:Query;export let models:Row[]=[];export let logs=false;export let periodOnly=false;export let onchange:(q:Query)=>void;
 let timer:ReturnType<typeof setTimeout>;onDestroy(()=>clearTimeout(timer));
 function update(key:string,value:any){query={...query,[key]:value,page:1};if(key==='period'){query.granularity=(value==='today'||value==='yesterday')?'hour':value==='all'?'week':'day';if(value!=='custom'){query.start='';query.end='';}}if(key==='mode'&&value==='model_call'&&query.tier==='mixed')query.tier='';onchange(query)}
 function search(value:string){clearTimeout(timer);timer=setTimeout(()=>update('search',value),250)}
</script>
<div class="filters" class:period-only={periodOnly} class:log-filters={logs}>
 <div class="filter-top"><div class="segments period-segments" role="group" aria-label={tr('周期')}>{#each [['today','今日'],['week','近 7 天'],['month','近 30 天'],['all','历史']].filter(([key])=>!logs||key!=='month') as [v,l]}<button class:active={query.period===v} aria-pressed={query.period===v} onclick={()=>update('period',v)}>{tr(l)}</button>{/each}{#if !periodOnly}<select aria-label={tr('自定义')} value={['yesterday','custom'].includes(query.period)?query.period:''} onchange={e=>update('period',e.currentTarget.value)}><option value="" disabled>{tr('自定义')}</option><option value="yesterday">{tr('昨天')}</option><option value="custom">{tr('自定义')}</option></select>{/if}</div>{#if logs}<div class="spacer"></div><div class="segments mode-segments" role="group" aria-label={tr('显示模式')}>{#each [['user_request','用户请求'],['model_call','模型调用']] as [v,l]}<button class:active={query.mode===v} aria-pressed={query.mode===v} onclick={()=>update('mode',v)}>{tr(l)}</button>{/each}</div><slot/>{/if}</div>
 {#if query.period==='custom'}<div class="row"><input type="date" aria-label="Start date" value={query.start} onchange={e=>update('start',e.currentTarget.value)}/><span>–</span><input type="date" aria-label="End date" value={query.end} onchange={e=>update('end',e.currentTarget.value)}/></div>{/if}
 {#if !periodOnly}<div class="filter-fields"><input list="model-suggestions" aria-label={tr('模型')} placeholder={tr('全部模型')} value={query.model} onchange={e=>update('model',e.currentTarget.value)}/><datalist id="model-suggestions">{#each rows(models) as m}<option value={m.model}>{m.model}</option>{/each}</datalist>{#if logs}<select aria-label={tr('速度')} value={query.tier} onchange={e=>update('tier',e.currentTarget.value)}><option value="">{tr('全部速度')}</option><option value="standard">Standard</option><option value="fast">Fast</option>{#if query.mode==='user_request'}<option value="mixed">Mixed</option>{/if}</select>{/if}{#if logs}<select aria-label={tr('状态')} value={query.status} onchange={e=>update('status',e.currentTarget.value)}><option value="">{tr('全部状态')}</option>{#each ['running','completed','aborted','unknown'] as v}<option value={v}>{v}</option>{/each}</select><input class="search" data-search aria-label={tr('搜索请求或聊天')} placeholder={tr('搜索请求或聊天')} value={query.search} oninput={e=>search(e.currentTarget.value)}/>{/if}</div>{/if}
</div>
