<script lang="ts">
 import{defaultQuery,rows,text,numeric,priced,stamp,kind,type Row,type Query}from'../lib/api';import{tr}from'../lib/i18n';import Filters from './Filters.svelte';import DetailPopover from './DetailPopover.svelte';import Model from './Model.svelte';import Duration from './Duration.svelte';
 export let data:Row={};export let query:Query=defaultQuery();export let models:Row[]=[];export let settings:Row={};export let onchange:(q:Query)=>void;export let onsave:(r:Row)=>Promise<void>;export let onerror:(e:any)=>void;
 let widths=[300,170,155,140,115];let drag:{index:number,start:number,width:number}|null=null;
 $: if(Array.isArray(settings.log_column_widths)) widths=settings.log_column_widths.slice(0,5);
 function begin(e:PointerEvent,index:number){e.preventDefault();drag={index,start:e.clientX,width:widths[index]};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
 function move(e:PointerEvent){if(drag)widths=widths.map((w,i)=>i===drag!.index?Math.max(80,Math.min(650,drag!.width+e.clientX-drag!.start)):w)}
 function end(){if(drag){drag=null;void onsave({log_column_widths:widths})}}
 function keyResize(e:KeyboardEvent,index:number){if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();widths=widths.map((w,i)=>i===index?Math.max(80,w+(e.key==='ArrowLeft'?-10:10)):w);void onsave({log_column_widths:widths})}}
</script>
<Filters {query} {models} logs {onchange}/>
<div class="logs-layout"><section class="ledger surface"><div class="table-scroll"><table style:width={`${widths.reduce((a,b)=>a+b,0)}px`}><colgroup>{#each widths as w}<col style:width={`${w}px`}/>{/each}</colgroup><thead><tr>{#each ['请求','模型','总 Token','费用','状态'] as h,i}<th>{tr(h)}<button type="button" class="column-handle" aria-label={`${tr(h)} width`} tabindex="0" onpointerdown={e=>begin(e,i)} onpointermove={move} onpointerup={end} onkeydown={e=>keyResize(e,i)}></button></th>{/each}</tr></thead><tbody>
{#each rows(data.rows) as r (r.id)}<tr><td><div class="details-row"><div class="request-text" title={text(r.prompt_preview??r.session_title)}>{r.record_kind==='automatic_approval_review'||r.record_kind==='context_compaction'?kind(r.record_kind):text(r.prompt_preview??r.session_title)}</div><DetailPopover id={String(r.id)} {onerror}/></div><small class="muted">{stamp(r.timestamp)} · {text(r.reasoning_effort)} · {text(r.service_tier)} · {r.model_context_window?numeric(r.model_context_window):'—'}</small></td><td><Model record={r}/></td><td>{numeric(r.total_tokens)}<small class="muted">{tr('输入')} {numeric(r.input_tokens)} · {tr('输出')} {numeric(r.output_tokens)}</small></td><td>{priced(r)}</td><td class:running={(r.request_status??r.status)==='running'}>{tr(text(r.status_label??r.request_status??r.status))}{#if r.duration_ms!=null}<small class="muted"><Duration milliseconds={r.duration_ms} running={(r.request_status??r.status)==='running'}/></small>{/if}</td></tr>{/each}
</tbody></table>{#if !rows(data.rows).length}<div class="empty">{tr('暂无数据')}</div>{/if}</div><footer class="ledger-footer"><div class="counts">{#each [['requests','用户请求'],['subagents','子代理'],['reviews','自动审批审查'],['compactions','上下文压缩'],['unassigned','未归属调用']] as [key,label]}<span>{tr(label)} {numeric(data.counts?.[key])}</span>{/each}</div><div class="row"><button disabled={query.page<=1} onclick={()=>onchange({...query,page:query.page-1})}>{tr('上一页')}</button><span>{data.page??query.page} / {Math.max(1,data.pages??1)}</span><button disabled={query.page>=Number(data.pages??1)} onclick={()=>onchange({...query,page:query.page+1})}>{tr('下一页')}</button></div></footer></section></div>
