<script lang="ts">
 import{tick,onDestroy}from'svelte';import{api,rows,text,numeric,compact,priced,number,percent,type Row}from'../lib/api';import{tr}from'../lib/i18n';import{toPng}from'html-to-image';
 export let initialPeriod='day';export let settings:Row={};export let onsave:(r:Row)=>Promise<void>;export let onclose:()=>void;export let onerror:(e:any)=>void;export let onpresent:()=>void;
 let period=initialPeriod;let style=settings.usage_report_style??'garden';let data:Row={};let busy=false;let exporting=false;let sequence=0;let card:HTMLElement;let exported='';let presented=false;
 const palettes:Record<string,string[]>={garden:['#FFFDF7','#173C31','#4C6959','#7CA88B','#C7DCC8','#F1BAA1','#F1F7EE'],bookmark:['#FFFBF4','#4E4032','#78634D','#C99B65','#E8D7AF','#EBAF86','#F7EFDD'],afternoon:['#FFFCF7','#493027','#785746','#DA855A','#F2C5AA','#D67650','#FEF1E8']};
 $: void load(period);
 $: summary=data.summary??{};
 $: top=rows(data.models).slice(0,3);
 $: slices=rows(data.time_slices).slice(0,4);
 $: peak=slices.length&&slices.some(s=>Number(s.requests)>0)?slices.reduce((best,r,i)=>Number(r.requests)>Number(slices[best].requests)?i:best,0):-1;
 $: biggest=Math.max(1,...slices.map(s=>Number(s.requests)||0));
 $: paper=palettes[style]??palettes.garden;
 $: height=Math.max(820,952-Math.max(0,3-top.length)*50);
 $: word=tr(period==='day'?'昨天':period==='week'?'上周':'上月');
 onDestroy(()=>sequence++);
 async function load(p:string){const ticket=++sequence;busy=true;try{const next=await api('GetReports',p);if(ticket===sequence){data=next;await tick();if(ticket===sequence&&!presented){presented=true;onpresent()}}}catch(e){if(ticket===sequence)onerror(e)}finally{if(ticket===sequence)busy=false}}
 async function selectStyle(value:string){style=value;await onsave({usage_report_style:value})}
 async function share(){exporting=true;try{await document.fonts.ready;const png=await toPng(card,{pixelRatio:2,cacheBust:false,backgroundColor:paper[6]});const saved=await api('SaveReportPNG',png,period);exported=text(saved.path);}catch(e){onerror(e)}finally{exporting=false}}
 function clock(value:any){if(value===null||value===undefined||value==='')return'—';const n=number(value);const d=new Date(n===null?value:n*1000);return Number.isFinite(d.getTime())?d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',hour12:false}):'—'}
</script>
<div class="report-backdrop"><div class="report-window" role="dialog" aria-modal="true" aria-label={tr('AI 使用报告')}><aside class="report-controls"><h2>{tr('AI 使用报告')}</h2>{#each [['day','日报'],['week','周报'],['month','月报']] as [p,label]}<button class:active={period===p} onclick={()=>{period=p;exported=''}}>{tr(label)}</button>{/each}<select aria-label={tr('样式')} value={style} onchange={e=>selectStyle(e.currentTarget.value)}>{#each [['garden','薄荷猫咪花园'],['bookmark','奶油猫尾书签'],['afternoon','杏色时段图']] as [s,l]}<option value={s}>{tr(l)}</option>{/each}</select><div class="spacer"></div><button class="primary" disabled={busy||exporting} onclick={share}>{tr(exporting?'处理中':'分享 PNG')}</button><button onclick={onclose}>{tr('关闭')}</button>{#if exported}<small class="export-note">{tr('导出完成')}<br/>{exported}</small>{/if}</aside>
<div class="report-scroll" aria-busy={busy}><article bind:this={card} class={`report-card ${style}`} style:min-height={`${height}px`} style:background={paper[6]} style:color={paper[1]} style={`--report-muted:${paper[2]};--report-accent:${paper[3]};--report-line:${paper[4]};--report-surface:${paper[6]}`}>
<svg class="report-paper" viewBox={`0 0 500 ${height}`} preserveAspectRatio="none" aria-hidden="true"><path d={`M18 80C16 58 28 10 42 19C57 11 96 67 123 75Q250 53 377 75C404 67 443 11 458 19C472 10 484 58 482 80L482 ${height-62}Q480 ${height-18} 428 ${height-18}L72 ${height-18}Q20 ${height-18} 18 ${height-62}Z`} fill={paper[0]} stroke={paper[4]}/><path d="M37 70Q48 34 60 44Q93 72 37 70M407 70Q418 34 430 44Q463 72 407 70" fill={paper[5]}/></svg>
<div class="report-content"><header class="report-card-header"><img src="/ReportCards/brand-mark.png" alt=""/><div><strong>Codexio</strong><span>{tr(period==='day'?'AI日报':period==='week'?'AI周报':'AI月报')}</span></div><time>{text(data.date_label)}</time></header>
<section class="report-hero"><h1>{peak>=0?`${word}，${tr(String(slices[peak].name))}${tr('最热闹')}`:`${word}${tr('没有请求记录')}`}</h1><div class="report-hero-detail"><div><strong>{peak>=0?numeric(slices[peak].requests)+' / '+numeric(summary.user_requests):numeric(summary.user_requests)}</strong><span>{tr('次请求')}</span><p>{peak>=0?`${tr(String(slices[peak].name))} · ${percent(Number(summary.user_requests)>0?Number(slices[peak].requests)/Number(summary.user_requests)*100:null)}`:''}</p></div><img class="report-art" src={`/ReportCards/cat-${style}.png`} alt=""/></div></section>
<div class="report-metrics">{#each [[priced(summary,'usd'),'费用'],[compact(summary.tokens),'总 Token'],[numeric(summary.user_requests),'用户请求'],[percent(summary.cache_hit_rate==null?null:Number(summary.cache_hit_rate)*100),'命中率']] as [value,label]}<div><strong>{value}</strong><span>{tr(label)}</span></div>{/each}</div>
<section class="report-rhythm"><div class="row between"><h2>{tr('使用节奏')}</h2><small>{peak>=0?tr(String(slices[peak].name))+tr('最活跃'):''}</small></div><div class="report-slices">{#each slices as slice,i}<div><strong>{numeric(slice.requests)}</strong><div class="slice-track"><span style:height={`${Math.max(2,Number(slice.requests)/biggest*48)}px`} style:background={i===peak?paper[3]:paper[4]}></span></div><small>{tr(String(slice.name))}</small></div>{/each}</div><div class="report-times"><span>{tr('最早')} · <strong>{clock(data.first)}</strong><br/>{tr('按自己的节奏来，喵')}</span><span>{tr('最晚')} · <strong>{clock(data.last)}</strong><br/>{tr('努力收好，好好放松喵')}</span></div></section>
<section class="report-models"><div class="row between"><h2>{tr('模型使用')}</h2><small>{numeric(summary.call_count??summary.requests)} {tr('次调用')}</small></div>{#each top as model}<div class="report-model-row"><span><strong>{text(model.model)}</strong><small>{priced(model,'usd')} · {compact(model.tokens)} Token</small></span><span>{numeric(model.call_count??model.requests)} {tr('次')} · {percent(Number(summary.requests)>0?Number(model.call_count??model.requests)/Number(summary.requests)*100:null)}</span></div>{/each}{#if !top.length}<p>{tr('暂无模型调用')}</p>{/if}</section>
<p class="report-discovery">{tr('小猫发现：')}{peak>=0?`${word}${tr('的请求在')}${tr(String(slices[peak].name))}${tr('最多，共 ')}${numeric(slices[peak].requests)}${tr(' 次。')}`:`${word}${tr('没有请求记录')}`}</p><footer>{tr('专注 · 与 AI 共成长')}</footer></div></article></div></div></div>
