<script lang="ts">
 import{api,text,iconPath,numeric,type Row}from'../lib/api';import{tr}from'../lib/i18n';import Floating from './Floating.svelte';import Mobile from './Mobile.svelte';
 export let settings:Row={};export let quota:Row={};export let onsave:(r:Row)=>Promise<void>;export let onerror:(e:any)=>void;export let onreload:()=>void;let section='appearance';let selectedIcon='';let roots='';let codexPath='';let update:Row={};let upstream:Row={};let busy=false;let restart=false;
 const icons=['main','01-teal-blue-gradient','02-violet-gradient-tile','03-graphite-relief','04-honey-orange','05-mint-ceramic','06-deep-ocean-aurora','07-ice-blue-glass','08-champagne-metal','09-cream-deboss','10-burgundy-enamel','11-obsidian-copper','12-moonlight-pearl'];
 $: if(!selectedIcon)selectedIcon=settings.app_icon??'main';
 $: roots=(settings.codex_roots??[]).join('\n');
 $: codexPath=settings.codex_path??'';
 $: update=settings.update??update;
 $: upstream=settings.upstream??upstream;
 async function act(name:string){busy=true;try{if(name==='CheckUpdate')update=await api(name);else await api(name);onreload()}catch(e){onerror(e)}finally{busy=false}}
 async function desktop(action:string){try{await api('DesktopAction',action)}catch(e){onerror(e)}}
 async function detect(enabled:boolean){busy=true;try{upstream=await api('UpstreamAction',enabled)}catch(e){onerror(e)}finally{busy=false}}
 function change(key:string,value:any){void onsave({[key]:value,...(key==='usage_refresh_interval_seconds'?{usage_refresh_interval_user_set:true}:{})})}
 function navMove(index:number,direction:number){const nav=[...(settings.navigation_order??['overview','logs','trends','subscription','pricing','settings'])];const to=index+direction;if(index>0&&to>0&&to<nav.length){[nav[index],nav[to]]=[nav[to],nav[index]];void onsave({navigation_order:nav})}}
</script>
<div class="settings-layout"><nav class="settings-sections" aria-label={tr('设置')}>{#each [['appearance','外观'],['floating','悬浮窗'],['data','数据'],['sync','同步'],['app','应用']] as [key,label]}<button class:active={section===key} onclick={()=>section=key}>{tr(label)}</button>{/each}</nav><div class="settings-content">
{#if section==='appearance'}<h2>{tr('外观')}</h2><label class="field"><span>{tr('主界面主题')}</span><select value={settings.theme??'system'} onchange={e=>change('theme',e.currentTarget.value)}>{#each [['system','跟随系统'],['light','浅色'],['dark','深色']] as [v,l]}<option value={v}>{tr(l)}</option>{/each}</select></label><label class="field"><span>{tr('语言')}</span><select value={settings.language??'zh'} onchange={e=>change('language',e.currentTarget.value)}><option value="zh">中文</option><option value="en">English</option></select></label><h3>{tr('应用图标')}</h3><div class="icon-picker">{#each icons as icon,i}<button class:selected={selectedIcon===icon} aria-label={`${tr('应用图标')} ${i+1}`} onclick={()=>selectedIcon=icon}><img src={iconPath(icon,true)} alt=""/></button>{/each}</div><div class="row"><button disabled={selectedIcon===settings.app_icon} onclick={()=>onsave({app_icon:selectedIcon})}>{tr('确认应用')}</button><button onclick={()=>selectedIcon=settings.app_icon??'main'}>{tr('取消选择')}</button></div><h3>{tr('导航顺序')}</h3>{#each settings.navigation_order??['overview','logs','trends','subscription','pricing','settings'] as item,i}<div class="row between navigation-setting"><span>{tr(({overview:'概览',logs:'日志',trends:'用量',subscription:'订阅',pricing:'定价',settings:'设置'} as Record<string,string>)[item])}</span><div class="row"><button disabled={i<=1} onclick={()=>navMove(i,-1)} aria-label="Move up">↑</button><button disabled={i===0||i===5} onclick={()=>navMove(i,1)} aria-label="Move down">↓</button></div></div>{/each}
{:else if section==='floating'}<h2>{tr('悬浮窗')}</h2><label class="field"><span>{tr('显示悬浮窗')}</span><input type="checkbox" checked={settings.widget_visible!==false} onchange={e=>change('widget_visible',e.currentTarget.checked)}/></label>{#each [['display_mode','显示模式',[['top','始终置顶'],['bottom','桌面底层'],['tray','仅托盘']]],['visual_style','悬浮窗样式',[['classic','经典'],['rings','双环'],['tiles','卡片'],['compact','紧凑'],['minimal','极简'],['orb','光球']]],['quota_scope','额度范围',[['auto','自动'],['both','5 小时与周额度'],['week','仅周额度']]],['dock_edge','贴边停靠',[['none','不贴边'],['top','顶部'],['bottom','底部'],['left','左侧'],['right','右侧']]]] as field}<label class="field"><span>{tr(String(field[1]))}</span><select value={settings[String(field[0])]} onchange={e=>change(String(field[0]),e.currentTarget.value)}>{#each field[2] as option}<option value={option[0]}>{tr(option[1])}</option>{/each}</select></label>{/each}{#each [['background_transparent','背景透明'],['show_border','显示边框']] as [key,label]}<label class="field"><span>{tr(label)}</span><input type="checkbox" checked={settings[key]} onchange={e=>change(key,e.currentTarget.checked)}/></label>{/each}<label class="field"><span>{tr('透明度')} {numeric(settings.background_opacity)}%</span><input type="range" min="0" max="100" value={settings.background_opacity??70} onchange={e=>change('background_opacity',Number(e.currentTarget.value))}/></label><label class="field"><span>{tr('边框颜色')}</span><input type="color" value={settings.border_color??'#8AB4F8'} onchange={e=>change('border_color',e.currentTarget.value)}/></label><Floating {settings} {quota} preview/><button onclick={()=>desktop('toggle-floating')}>{tr('显示悬浮窗')}</button>
{:else if section==='data'}<h2>{tr('数据')}</h2><label class="field vertical"><span>{tr('本机日志目录')}</span><textarea rows="3" bind:value={roots} onblur={()=>onsave({codex_roots:roots.split('\n').map(s=>s.trim()).filter(Boolean)})}></textarea></label><label class="field vertical"><span>{tr('Codex 可执行文件')}</span><input placeholder={tr('自动发现 Codex')} bind:value={codexPath} onblur={()=>onsave({codex_path:codexPath})}/></label><div class="row"><button disabled={busy} onclick={()=>act('Rescan')}>{tr('重新扫描')}</button><button onclick={()=>desktop('open-data')}>{tr('打开数据目录')}</button></div><p class="muted path">{text(settings.data_path)}</p><h3>{tr('AI 使用报告')}</h3><button onclick={()=>desktop('open-reports')}>{tr('打开报告目录')}</button><label class="check"><input type="checkbox" checked={settings.usage_report_auto!==false} onchange={e=>change('usage_report_auto',e.currentTarget.checked)}/>{tr('每天 08:00 后首次打开时显示')}</label><label class="field"><span>{tr('样式')}</span><select value={settings.usage_report_style??'garden'} onchange={e=>change('usage_report_style',e.currentTarget.value)}><option value="garden">{tr('花园')}</option><option value="bookmark">{tr('书签')}</option><option value="afternoon">{tr('午后')}</option></select></label>
{:else if section==='sync'}<h2>{tr('同步')}</h2><Mobile initial={settings.mobile??{}} {onerror}/>
{:else}<h2>Codexio {text(settings.version)}</h2><section class="surface"><div class="row between"><h3>{tr('应用更新')}</h3><button disabled={busy} onclick={()=>act('CheckUpdate')}>{tr('检查更新')}</button></div><label class="check"><input type="checkbox" checked={settings.auto_update!==false} onchange={e=>change('auto_update',e.currentTarget.checked)}/>{tr('自动检查更新')}</label><p>{text(update.status)}{update.version?' · '+update.version:''}</p>{#if update.progress!=null}<progress max="100" value={Number(update.progress)}></progress>{/if}{#if update.error}<p class="error">{update.error}</p>{/if}{#if update.notes}<p>{update.notes}</p>{/if}{#if ['available','ready','downloaded'].includes(update.status)}<div class="row"><button class="primary" disabled={busy||settings.mock} onclick={()=>act('InstallUpdate')}>{tr('立即更新')}</button><button onclick={()=>act('DeferUpdate')}>{tr('稍后')}</button></div>{/if}{#if update.url}<button onclick={()=>api('OpenURL',update.url).catch(onerror)}>{tr('打开下载页面')}</button>{/if}</section><section class="surface"><div class="row between"><h3>{tr('上游检测')}</h3><input type="checkbox" aria-label={tr('上游检测')} checked={upstream.enabled??settings.upstream_detection_enabled??false} disabled={busy} onchange={e=>detect(e.currentTarget.checked)}/></div><p class="muted">{tr('保留当前模型供应商与认证方式。仅显示响应实际返回的模型型号，历史请求无法补查；退出 Codexio 会恢复配置。')}</p><p>{text(upstream.status)}{upstream.error?' · '+upstream.error:''}</p>{#if upstream.restart_required}<button onclick={()=>restart=true}>{tr('重启 Codex 客户端')}</button>{/if}</section><section class="surface"><h3>{tr('刷新间隔')}</h3>{#each [['refresh_interval_seconds','额度',[30,60,300]],['usage_refresh_interval_seconds','日志数据',[5,10,30,60]],['week_estimate_interval_minutes','额度估算',[10,30,60]]] as field}<label class="field"><span>{tr(String(field[1]))}</span><select value={settings[String(field[0])]} onchange={e=>change(String(field[0]),Number(e.currentTarget.value))}>{#each field[2] as value}<option value={value}>{value} {field[0]==='week_estimate_interval_minutes'?tr('分钟'):'s'}</option>{/each}</select></label>{/each}</section><section class="surface"><h3>{tr('窗口')}</h3><div class="row wrap"><button onclick={()=>desktop('close-main')}>{tr('关闭窗口')}</button><button onclick={()=>desktop('toggle-floating')}>{tr('显示悬浮窗')}</button><button onclick={()=>desktop('quit')}>{tr('退出 Codexio')}</button></div></section>{/if}</div></div>{#if restart}<div class="modal-backdrop"><div class="modal"><h2>{tr('重启 Codex 客户端')}</h2><p>{tr('重启会关闭当前 Codex 窗口，请先保存工作。')}</p><div class="row"><button onclick={()=>{restart=false;void desktop('restart-client')}}>{tr('重启 Codex 客户端')}</button><button onclick={()=>restart=false}>{tr('稍后')}</button></div></div></div>{/if}
