<script lang="ts">
 import{onDestroy}from'svelte';import{api,rows,text,numeric,cost,percent,stamp,utcReportStamp,number,type Row}from'../lib/api';import{tr}from'../lib/i18n';import Quota from './Quota.svelte';
 export let data:Row={};export let settings:Row={};export let onsave:(r:Row)=>Promise<void>;export let onreload:()=>void;export let onerror:(e:any)=>void;
 let credit:Row|null=null;let busy=false;let editing=false;let profile:Row={};let resetResult='';let selectedAccount='';let expiryTimer:ReturnType<typeof setTimeout>;
 let expandedCycle='';let estimatesOpen=true;
 function utcDay(value:any){return utcReportStamp(value,true)}
 async function refreshReports(){try{await api('RefreshAccountReports');onreload()}catch(e){onerror(e)}}
 $: accountKey=String(data.account_key??'');
 $: if(credit){const current=credits.find(c=>c.id===credit?.id);if(accountKey!==selectedAccount||!current||!usable(current))dismiss();}
 onDestroy(()=>clearTimeout(expiryTimer));
 function expiry(c:Row){const n=number(c.expires_at);return n===null?null:(n<1e12?n*1000:n)}
 function usable(c:Row){const deadline=expiry(c);return c.status==='available'&&!!c.id&&c.expiry_known===true&&(deadline===null||deadline>Date.now())}
 function dismiss(){clearTimeout(expiryTimer);credit=null;selectedAccount=''}
 function choose(c:Row){if(!usable(c)||settings.mock||!accountKey)return;clearTimeout(expiryTimer);credit=c;selectedAccount=accountKey;const deadline=expiry(c);if(deadline!==null)expiryTimer=setTimeout(dismiss,Math.max(0,Math.min(2147483647,deadline-Date.now())))}
 function focusDialog(node:HTMLElement){const previous=document.activeElement as HTMLElement|null;const buttons=()=>Array.from(node.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));queueMicrotask(()=>buttons()[0]?.focus());const key=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=buttons();if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};node.addEventListener('keydown',key);return{destroy(){node.removeEventListener('keydown',key);previous?.focus()}}}
 function deadline(c:Row){return c.expiry_known===true&&c.expires_at==null?tr('无到期限制'):c.expires_at?stamp(c.expires_at):tr('截止时间未提供')}
 $: credits=rows(data.credits?.details??data.reset_credit_details??data.credits);
 $: cycles=rows(data.cycles??data.reports?.plan?.cycles);
 $: observations=rows(data.rolling_estimates?.rows??data.rolling_estimates??data.weekly_estimates).slice(0,20);
 function edit(){profile={...(settings.subscription_profile??{})};editing=true}
 async function reset(){if(!credit||busy||settings.mock||selectedAccount!==accountKey||!usable(credit)){dismiss();return}const id=String(credit.id);busy=true;try{const result=await api('ResetCreditForAccount',id,selectedAccount);resetResult=text(result.message??result.status,'');dismiss();onreload()}catch(e){onerror(e)}finally{busy=false}}
 async function save(){await onsave({subscription_profile:{...profile,price_usd:profile.price_usd===''?null:profile.price_usd}});editing=false}

</script>
<svelte:window onkeydown={e=>{if(e.key==='Escape'&&!busy)dismiss()}}/>
<section class="profile"><div class="row between"><div><h2>{text(settings.subscription_profile?.plan||data.plan_type)}</h2><span class="muted">{text(data.account?.name??data.account?.email)}{settings.subscription_profile?.renewal_date?' · '+tr('续费日期')+' '+settings.subscription_profile.renewal_date:''}</span></div><button onclick={edit}>{tr('个人订阅资料')}</button></div>{#if settings.subscription_profile?.price_usd!=null}<strong>{cost(settings.subscription_profile.price_usd)}</strong>{/if}</section>
<Quota quota={data}/>

<section class="plan-history"><div class="row between"><h3>{tr('套餐用量历史')}</h3><small class="muted">{tr('按模型')}</small></div><div class="cycle-table"><div class="row between cycle-heading"><span>{tr('周期')}</span><span>{tr('已使用限额百分比')}</span></div>{#each cycles as cycle,index}<details class="cycle-detail" open={expandedCycle?expandedCycle===String(cycle.id??cycle.start):index===0}><summary onclick={e=>{e.preventDefault();const key=String(cycle.id??cycle.start);const open=expandedCycle?expandedCycle===key:index===0;expandedCycle=open?'closed':key;}} title={utcReportStamp(cycle.start)+' – '+utcReportStamp(cycle.end)}><span>{utcDay(cycle.start)} – {utcDay(cycle.end)}</span><strong>{cycle.approximate?tr('约 '):''}{percent(cycle.used_percent)}</strong></summary><div class="cycle-meta"><span>{utcReportStamp(cycle.start)} – {utcReportStamp(cycle.end)}</span><span>{tr('统计截至')} {utcReportStamp(cycle.data_as_of)}</span></div>{#each rows(cycle.models) as model}<div class="row between model-breakdown"><span>{text(model.model??model.key)}</span><span>{percent(model.used_percent)}</span></div>{/each}{#if cycle.accounting_complete!==true||cycle.coverage_complete!==true}<small class="muted">{tr('部分数据')}</small>{/if}</details>{/each}</div>{#if data.reports?.error}<p class="muted">{data.reports.error}</p>{/if}{#if !cycles.length}<p class="muted">{tr('当前账户尚未提供周期明细')}</p><button onclick={refreshReports}>{tr('刷新明细')}</button>{/if}</section>
<section class="reset-section"><div class="row between"><h3>{tr('主动重置')}</h3><span>{tr('剩余')} {numeric(data.credits?.available_count??data.reset_credits)}</span></div>{#each credits as c}<div class="credit-row"><div><strong>{text(c.title??c.name??c.reset_type,tr('额度'))}</strong><small class="muted">{tr('截止时间')} · {deadline(c)}</small></div><button disabled={busy||settings.mock||!accountKey||!usable(c)} onclick={()=>choose(c)}>{tr(c.status==='redeeming'?'处理中':c.status==='redeemed'?'已使用':'使用重置')}</button></div>{/each}{#if !credits.length}<p class="muted">{tr('只显示服务端已提供的重置明细')}</p>{/if}{#if resetResult}<p>{resetResult}</p>{/if}</section>
<details class="local-estimates" bind:open={estimatesOpen}><summary>{tr('周额度估算')}</summary><section><h3>{tr('周额度估值记录')}</h3><div class="estimate-list">{#each observations as observation}<div class="estimate-row"><span>{stamp(observation.start,true)} – {stamp(observation.end,true)}</span><span><strong>{percent(observation.delta_percent)}</strong><b>{cost(observation.estimated_total_usd)}</b></span></div>{:else}<div class="estimate-empty">{tr('暂无数据')}</div>{/each}</div><p class="muted estimate-note">{tr('整周估值依据本机消费与账户额度变化，仅供参考')}</p></section>
</details>
{#if credit}<div class="modal-backdrop"><div class="modal reset-confirmation" use:focusDialog role="alertdialog" aria-modal="true" aria-labelledby="reset-title" aria-describedby="reset-description"><h2 id="reset-title">{tr('使用这次额度重置？')}</h2><div id="reset-description"><p class="reset-account">{text(data.account?.email??data.account?.name)}</p><p><strong>{text(credit.title??credit.name??credit.reset_type)}</strong><br/><span class="muted">{tr('截止时间')} · {deadline(credit)}</span></p><p class="reset-warning">{tr('这会消耗所选重置，无法撤销。')}</p></div><div class="row modal-actions"><button disabled={busy} onclick={dismiss}>{tr('取消')}</button><button class="primary" disabled={busy||settings.mock} onclick={reset}>{tr('使用重置')}</button></div></div></div>{/if}
{#if editing}<div class="modal-backdrop"><form class="modal" onsubmit={e=>{e.preventDefault();void save()}}><h2>{tr('个人订阅资料')}</h2><label class="field"><span>{tr('套餐')}</span><input maxlength="64" bind:value={profile.plan}/></label><label class="field"><span>{tr('价格 USD')}</span><input type="number" min="0" step="any" bind:value={profile.price_usd}/></label><label class="field"><span>{tr('续费日期')}</span><input type="date" bind:value={profile.renewal_date}/></label><div class="row"><button class="primary">{tr('保存')}</button><button type="button" onclick={()=>editing=false}>{tr('取消')}</button></div></form></div>{/if}
<style>
.profile{padding:0;background:transparent;border:0;margin:0}.profile h2{font-size:14px;margin:0 0 4px}.profile .muted{font-size:11px}.profile button{font-size:11px;min-height:26px}.profile>strong{display:none}.plan-history{display:flex;flex-direction:column;gap:10px;order:0}.plan-history h3,.reset-section h3{font-size:18px;margin:0}.cycle-table{border:1px solid var(--border);border-radius:18px;overflow:hidden}.cycle-heading{padding:13px 20px;background:color-mix(in srgb,var(--text) 5.5%,transparent);font-size:11px;color:var(--muted)}.cycle-detail{padding:0 20px;border-top:1px solid var(--border);font-size:12px}.cycle-detail summary{cursor:pointer;display:flex;justify-content:space-between;gap:10px;align-items:center;min-height:57px;font-size:14px;list-style:none}.cycle-detail summary::before{content:'›';color:var(--muted);width:12px}.cycle-detail[open] summary::before{content:'⌄'}.cycle-detail summary>span{flex:1}.cycle-detail summary strong{font-weight:500;white-space:nowrap}.cycle-meta{display:flex;flex-direction:column;gap:5px;margin:0 0 12px 23px;color:var(--muted);font-size:11px}.model-breakdown{font-size:13px;margin:8px 0 8px 23px;color:var(--muted)}.cycle-detail>small{display:block;margin:10px 0 14px 23px}.local-estimates>summary{font-size:15px;font-weight:500;cursor:pointer;padding:5px 0}.local-estimates>section{padding:12px 0 0}.local-estimates h3{font-size:18px;margin:0 0 10px}.estimate-list{border-top:1px solid var(--border)}.estimate-row{display:flex;justify-content:space-between;gap:24px;align-items:center;min-height:72px;border-bottom:1px solid var(--border);font-size:14px}.estimate-row>span:first-child{color:var(--muted)}.estimate-row>span:last-child{display:flex;gap:18px;align-items:baseline;white-space:nowrap}.estimate-row strong{font-weight:400}.estimate-row b{font-size:15px}.estimate-empty{padding:20px 0;border-bottom:1px solid var(--border);color:var(--muted)}.estimate-note{font-size:12px;margin-top:12px}.reset-section{font-size:12px}.credit-row{padding:12px 0}.credit-row strong{font-size:13px}.credit-row small{font-size:12px}@media(max-width:620px){.estimate-row{align-items:flex-start;flex-direction:column;gap:7px;padding:13px 0}.estimate-row>span:last-child{width:100%;justify-content:space-between}}
</style>
