<script lang="ts">
 import{api,rows,text,numeric,cost,percent,stamp,number,type Row}from'../lib/api';import{tr}from'../lib/i18n';import Quota from './Quota.svelte';
 export let data:Row={};export let settings:Row={};export let onsave:(r:Row)=>Promise<void>;export let onreload:()=>void;export let onerror:(e:any)=>void;
 let credit:Row|null=null;let busy=false;let editing=false;let profile:Row={};let resetResult='';let historyPage=1;
 $: credits=rows(data.credits?.details??data.reset_credit_details??data.credits);
 $: cycles=rows(data.cycles??data.reports?.plan?.cycles);
 $: observations=rows(data.rolling_estimates?.rows??data.rolling_estimates??data.weekly_estimates).slice(0,100);
 $: historyPages=Math.max(1,Math.ceil(observations.length/10));
 $: historyPage=Math.min(historyPage,historyPages);
 function edit(){profile={...(settings.subscription_profile??{})};editing=true}
 async function reset(){if(!credit)return;busy=true;try{const result=await api('ResetCredit',String(credit.id));resetResult=text(result.message??result.status,'');credit=null;onreload()}catch(e){onerror(e)}finally{busy=false}}
 async function save(){await onsave({subscription_profile:{...profile,price_usd:profile.price_usd===''?null:profile.price_usd}});editing=false}
 function leftTime(value:any){const n=number(value);if(n===null)return'';const ms=n*1000-Date.now();return ms<=0?tr('已过期'):Math.ceil(ms/86400000)+' '+tr('天')}
</script>
<section class="surface profile"><div class="row between"><div><h2>{text(settings.subscription_profile?.plan||data.plan_type)}</h2><span class="muted">{text(data.account?.name??data.account?.email)}{settings.subscription_profile?.renewal_date?' · '+tr('续费日期')+' '+settings.subscription_profile.renewal_date:''}</span></div><button onclick={edit}>{tr('个人订阅资料')}</button></div>{#if settings.subscription_profile?.price_usd!=null}<strong>{cost(settings.subscription_profile.price_usd)}</strong>{/if}</section>
<Quota quota={data} rings/>
<section class="surface"><div class="row between"><h3>{tr('主动重置')}</h3><span>{tr('剩余')} {numeric(data.credits?.available_count??data.reset_credits)}</span></div>{#each credits as c}<div class="credit-row"><div><strong>{text(c.title??c.name??c.reset_type,tr('额度'))}</strong><small class="muted">{c.expiry_known===true&&c.expires_at==null?tr('无到期限制'):c.expires_at?stamp(c.expires_at):tr('截止时间未提供')}</small>{#if c.expires_at}<small>{leftTime(c.expires_at)}</small>{/if}{#if c.description}<small class="muted">{c.description}</small>{/if}</div><button disabled={busy||c.status!=='available'||!c.id} onclick={()=>credit=c}>{tr(c.status==='redeeming'?'处理中':c.status==='redeemed'?'已使用':'使用重置')}</button></div>{/each}{#if !credits.length}<p class="muted">{tr('只显示服务端已提供的重置明细')}</p>{/if}{#if resetResult}<p>{resetResult}</p>{/if}</section>
<section class="surface"><h3>{tr('参考估值')}</h3><div class="row estimate"><strong>{cost(data.estimate?.usd)}</strong><span class="muted">{text(data.estimate?.status)}</span></div></section>
<section class="surface"><h3>{tr('套餐用量历史')}</h3>{#each cycles as cycle}<details class="cycle-detail"><summary><span>{stamp(cycle.start,true)} – {stamp(cycle.end,true)}</span><strong>{percent(cycle.used_percent)}</strong></summary><div class="row between"><small class="muted">{tr('统计截至')} {stamp(cycle.data_as_of,true)}</small><small class="warning">{cycle.approximate?tr('近似值'):''}{cycle.accounting_complete===false?' · '+tr('数据不完整'):''}</small></div>{#each rows(cycle.models) as model}<div class="row between model-breakdown"><span>{text(model.model??model.key)}</span><span>{percent(model.used_percent??model.percent??(model.basis_points==null?null:Number(model.basis_points)/100))}</span></div>{/each}{#if !rows(cycle.models).length}<p class="muted">{tr('暂无模型明细')}</p>{/if}</details>{/each}{#if !cycles.length}<div class="empty small">{tr('暂无数据')}</div>{/if}</section>
<section class="surface"><h3>{tr('周额度估值记录')}</h3><div class="table-scroll"><table class="estimate-table"><thead><tr>{#each ['套餐','采样时间段','额度','总 Token','费用','周估值'] as h}<th>{tr(h)}</th>{/each}</tr></thead><tbody>{#each observations.slice((historyPage-1)*10,historyPage*10) as o}<tr><td>{text(o.plan_type)}</td><td>{stamp(o.start,true)}<br/>{stamp(o.end,true)}</td><td>{percent(o.start_percent)} → {percent(o.end_percent)}</td><td>{numeric(o.consumed_tokens)}</td><td>{cost(o.consumed_usd)}</td><td>{cost(o.estimated_total_usd)}</td></tr>{/each}</tbody></table></div>{#if !observations.length}<div class="empty small">{tr('暂无数据')}</div>{/if}{#if historyPages>1}<div class="row"><button disabled={historyPage<=1} onclick={()=>historyPage--}>{tr('上一页')}</button><span>{historyPage} / {historyPages}</span><button disabled={historyPage>=historyPages} onclick={()=>historyPage++}>{tr('下一页')}</button></div>{/if}<p class="muted">{tr('仅使用本地日志与同期额度观测估值；非订阅实际扣款。')}</p></section>
<section class="surface"><h3>{tr('官方报告')}</h3>{#each rows(data.official_reports??data.reports?.rows) as report}<details class="cycle-detail"><summary><span>{text(report.title??report.name)}</span><strong>{percent(report.used_percent)}</strong></summary><small class="muted">{tr('统计截至')} {stamp(report.data_as_of,true)}</small>{#if report.balance_usage_credits!=null}<p>{tr('额度')} {numeric(report.balance_usage_credits)}</p>{/if}{#each rows(report.groups) as group}<div class="row between official-group"><span>{text(group.model??group.name)}<small class="muted">{text(group.reasoning_effort??group.effort)} · {text(group.service_tier??group.speed)}</small></span><span>{percent(group.weekly_limit_percent??group.used_percent)}<small class="muted">5h {percent(group.five_hour_limit_percent)}</small></span></div>{/each}{#if !rows(report.groups).length}<p class="muted">{tr('暂无模型明细')}</p>{/if}</details>{/each}{#if data.reports?.error}<p class="error">{data.reports.error}</p>{/if}{#if !rows(data.official_reports??data.reports?.rows).length}<p class="muted">{tr('暂无数据')}</p>{/if}</section>
{#if credit}<div class="modal-backdrop"><div class="modal" role="alertdialog" aria-modal="true" aria-label={tr('使用这次额度重置？')}><h2>{tr('使用这次额度重置？')}</h2><p>{text(credit.title??credit.name??credit.reset_type)}<br/>{stamp(credit.expires_at)}</p><div class="row"><button class="primary" disabled={busy} onclick={reset}>{tr('使用重置')}</button><button disabled={busy} onclick={()=>credit=null}>{tr('取消')}</button></div></div></div>{/if}
{#if editing}<div class="modal-backdrop"><form class="modal" onsubmit={e=>{e.preventDefault();void save()}}><h2>{tr('个人订阅资料')}</h2><label class="field"><span>{tr('套餐')}</span><input maxlength="64" bind:value={profile.plan}/></label><label class="field"><span>{tr('价格 USD')}</span><input type="number" min="0" step="any" bind:value={profile.price_usd}/></label><label class="field"><span>{tr('续费日期')}</span><input type="date" bind:value={profile.renewal_date}/></label><div class="row"><button class="primary">{tr('保存')}</button><button type="button" onclick={()=>editing=false}>{tr('取消')}</button></div></form></div>{/if}
